# Generated by Django 2.2.5 on 2019-10-09 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20191001_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=15)),
                ('antena', models.CharField(max_length=10)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('code', models.TextField()),
                ('objeto', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='objeto',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='server',
            field=models.CharField(max_length=15),
        ),
    ]
