# Generated by Django 2.2.5 on 2019-10-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_auto_20191010_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='code',
            field=models.TextField(),
        ),
    ]
